/**
 * Maps Magento mgs_brand IDs → brand logo paths.
 */
export const BRAND_LOGOS: Record<number, string> = {
  817: "/brands/mgs_brand/g/o/goodyear_1_1_.png",
  818: "/brands/mgs_brand/c/o/continental.png",
  826: "/brands/mgs_brand/a/c/accelera.png",
  829: "/brands/mgs_brand/a/l/altenzo-logo_1.jpg",
  831: "/brands/mgs_brand/a/r/armstrong-logo.png",
  834: "/brands/mgs_brand/a/t/atlas.jpg",
  835: "/brands/mgs_brand/a/t/atturo.png",
  836: "/brands/mgs_brand/b/e/bearway-logo_1.jpg",
  837: "/brands/mgs_brand/b/f/bfgoodrich_1.png",
  843: "/brands/mgs_brand/c/o/coperatie_1.png",
  844: "/brands/mgs_brand/d/e/deestone.png",
  845: "/brands/mgs_brand/d/u/dunlop_1.png",
  848: "/brands/mgs_brand/f/a/falken_1.png",
  849: "/brands/mgs_brand/b/r/bride_1.png",
  861: "/brands/mgs_brand/h/a/hankok_1_1.png",
  868: "/brands/mgs_brand/k/a/kapsen-logo.jpg",
  870: "/brands/mgs_brand/k/u/kumho-logo_1.png",
  871: "/brands/mgs_brand/l/a/landsail-logo_1.jpg",
  872: "/brands/mgs_brand/l/a/land-spider_1.jpg",
  873: "/brands/mgs_brand/l/a/lassalogo.jpg",
  874: "/brands/mgs_brand/l/a/laufenn-logo.png",
  875: "/brands/mgs_brand/l/e/leao-logo_1.png",
  882: "/brands/mgs_brand/m/a/matrax-tyres-uae.png",
  884: "/brands/mgs_brand/m/a/maxxis.png",
  885: "/brands/mgs_brand/m/e/metzeler-logo_1_.png",
  886: "/brands/mgs_brand/m/i/michelin_1.png",
  887: "/brands/mgs_brand/b/f/bfgoodrich_1.png",
  892: "/brands/mgs_brand/n/e/nexen_1_1.png",
  894: "/brands/mgs_brand/n/e/nexen_1_1.png",
  895: "/brands/mgs_brand/t/o/toyo_1.png",
  899: "/brands/mgs_brand/p/i/pirelli_1.png",
  900: "/brands/mgs_brand/p/r/prinx-tires-logo.jpg",
  902: "/brands/mgs_brand/m/i/michelin_1.png",
  903: "/brands/mgs_brand/r/o/roadstone_1.png",
  904: "/brands/mgs_brand/r/o/roadking.png",
  905: "/brands/mgs_brand/r/o/roadstone_1.png",
  906: "/brands/mgs_brand/r/o/roadstone_1.png",
  907: "/brands/mgs_brand/r/o/roadx-logo_1.png",
  908: "/brands/mgs_brand/r/o/rotalla-logo.jpg",
  909: "/brands/mgs_brand/s/a/sailun-logo_1.jpg",
  910: "/brands/mgs_brand/s/e/seam-tyre-logo.png",
  911: "/brands/mgs_brand/s/u/sunny_1.jpg",
  912: "/brands/mgs_brand/d/u/dunlop_1.png",
  913: "/brands/mgs_brand/s/u/sunny_1.jpg",
  915: "/brands/mgs_brand/t/o/toyo_1.png",
  916: "/brands/mgs_brand/t/o/toyo_1.png",
  917: "/brands/mgs_brand/t/r/tracmax-tyres.jpg",
  918: "/brands/mgs_brand/z/e/zeetax_1.png",
  919: "/brands/mgs_brand/v/i/vitour-logo.jpg",
  921: "/brands/mgs_brand/v/r/vredestein.jpg",
  922: "/brands/mgs_brand/w/a/wanli-logo.jpg",
  924: "/brands/mgs_brand/w/i/windforce-logo_1.png",
  925: "/brands/mgs_brand/w/i/winrun.png",
  926: "/brands/mgs_brand/y/o/yokoma_1.png",
  927: "/brands/mgs_brand/z/e/zeetax_1.png",
  928: "/brands/mgs_brand/z/e/zeta-logo.jpg",
  929: "/brands/mgs_brand/k/u/kumho-logo_1.png",
  930: "/brands/mgs_brand/z/e/zextour-logo.jpg",
  933: "/brands/mgs_brand/a/p/apollo-tyres.png",
  934: "/brands/mgs_brand/b/r/bride_1.png",
  937: "/brands/mgs_brand/t/o/toyo_1.png",
  1458: "/brands/mgs_brand/a/n/annaite-logo_1.jpg",
  1465: "/brands/mgs_brand/l/a/lanvigator_1.jpg",
  1470: "/brands/mgs_brand/t/e/teraflex.jpg",
  1507: "/brands/mgs_brand/l/o/longway_1.jpg",
  1518: "/brands/mgs_brand/f/o/forceum_1.jpg",
  1519: "/brands/mgs_brand/d/u/duraman-tyres_1.jpg",
  1520: "/brands/mgs_brand/k/i/kingboss.jpg",
  1530: "/brands/mgs_brand/d/o/double-coin_1.jpg",
  1531: "/brands/mgs_brand/d/o/doublestar-tyres_1.jpg",
  1546: "/brands/mgs_brand/k/u/kustone_1.jpg",
  1553: "/brands/mgs_brand/a/t/atlander-tyres_1.jpg",
  1554: "/brands/mgs_brand/m/i/mileking-tyre_1.jpg",
  1567: "/brands/mgs_brand/g/r/grandstone_5ca3d3091adf4.jpg",
  1568: "/brands/mgs_brand/r/o/rockblade_1.jpg",
  1579: "/brands/mgs_brand/c/o/comoro-tyres-dubai_1.jpeg",
  1799: "/brands/mgs_brand/f/o/forceland_1_.png",
  1898: "/brands/mgs_brand/c/o/compasal_1.jpg",
  1899: "/brands/mgs_brand/r/o/royal-black_1__1.png",
  1900: "/brands/mgs_brand/s/a/sailun-logo_1.jpg",
  1906: "/brands/mgs_brand/p/e/petlas_1.jpg",
  1941: "/brands/mgs_brand/g/e/gepormax.jpg",
  1944: "/brands/mgs_brand/a/m/amaron_logo_0.jpg",
  2412: "/brands/mgs_brand/b/l/blackrhino_1__1_.png",
  2415: "/brands/mgs_brand/f/u/fuel_1_.png",
  2418: "/brands/mgs_brand/l/e/lenso-wheels-logo_1_.png",
  2422: "/brands/mgs_brand/r/o/rotiform_1_.png",
  2423: "/brands/mgs_brand/v/i/vision_1_.jpg",
  3185: "/brands/mgs_brand/b/o/bosch_1_.png",
  3186: "/brands/mgs_brand/d/a/dagenite_1_.jpg",
  3187: "/brands/mgs_brand/d/u/duracell_1_.jpg",
  3188: "/brands/mgs_brand/f/i/fiamm_1_.jpg",
  3190: "/brands/mgs_brand/s/o/solite_1_.jpg",
  3191: "/brands/mgs_brand/v/a/varta_1_.jpg",
  3192: "/brands/mgs_brand/v/o/volcan_1_.png",
  3525: "/brands/mgs_brand/a/r/arivo_1.jpg",
  3528: "/brands/mgs_brand/l/i/linglong_1.jpg",
  3530: "/brands/mgs_brand/z/e/zelda.jpg",
  3997: "/brands/mgs_brand/g/i/giti_1.jpg",
  4026: "/brands/mgs_brand/a/u/austone-tires.png",
  4042: "/brands/mgs_brand/r/a/radar.png",
  4061: "/brands/mgs_brand/r/o/roadking.png",
  4062: "/brands/mgs_brand/a/r/arroyo-logo.png",
  4063: "/brands/mgs_brand/i/m/imperial_1__1.jpg",
  4065: "/brands/mgs_brand/s/o/sonix_1.jpg",
  4066: "/brands/mgs_brand/c/e/ceros.png",
  4110: "/brands/mgs_brand/o/t/otani.jpg",
  4184: "/brands/mgs_brand/s/e/sensus.jpg",
  4242: "/brands/mgs_brand/v/e/venom.png",
  4276: "/brands/mgs_brand/y/o/yomar.png",
  4283: "/brands/mgs_brand/c/s/cst_1_.jpg",
  4508: "/brands/mgs_brand/d/u/duraman-tyres_1.jpg",
  4509: "/brands/mgs_brand/a/r/arivo_1.jpg",
  4510: "/brands/mgs_brand/k/u/kumho-logo_1.png",
  4511: "/brands/mgs_brand/c/o/comoro-tyres-dubai_1.jpeg",
  4512: "/brands/mgs_brand/b/l/blackrhino_1__1_.png",
  4513: "/brands/mgs_brand/b/r/bride_1.png",
  4807: "/brands/mgs_brand/s/u/sunny_1.jpg",
};

/**
 * Maps Magento brand attribute option IDs → brand names.
 */
export const BRAND_NAMES: Record<number, string> = {
  3183: "AC Delco",
  4799: "Alpha",
  2408: "American Racing",
  4800: "Anchee",
  1897: "Arduzza",
  4514: "Arisun",
  3525: "Arivo",
  4509: "Arivo",
  4062: "Arroyo",
  2409: "Asanti",
  3184: "Asimco",
  1553: "Atlander",
  2410: "ATX",
  4026: "Austone",
  2101: "Avon",
  2411: "Big Bull",
  4512: "Black Bear",
  2412: "Black Rhino",
  3185: "Bosch",
  4064: "Centara",
  4066: "Ceros",
  4511: "Comforser",
  1579: "Comoro",
  1898: "Compasal",
  3186: "Dagenite",
  4801: "Didar",
  3187: "Duracell",
  4508: "Dynamo",
  2413: "F-Power",
  4802: "Farroad",
  3188: "Fiamm",
  4513: "Firestone",
  1799: "Forceland",
  2414: "FR",
  4877: "Friezza",
  2415: "Fuel",
  2416: "G-FX",
  3526: "Galaxia",
  1941: "Gepormax",
  3997: "Giti",
  1567: "Grandstone",
  4803: "Greentrack",
  1943: "Grenlander",
  4063: "Imperial",
  4510: "Kenda",
  2417: "KMC Wheels",
  4241: "Krain",
  1546: "Kustone",
  2418: "Lenso",
  3528: "Linglong",
  1554: "Mileking",
  2102: "Mitas",
  2419: "Motegi Racing",
  2420: "Moto Metal",
  4518: "Nama",
  2421: "Niche",
  4110: "Otani",
  1906: "Petlas",
  4042: "Radar",
  4061: "Road King",
  4804: "Roadboss",
  1568: "Rockblade",
  2422: "Rotiform",
  1899: "Royal Black",
  3529: "Sahara",
  1900: "Sailun",
  4805: "Sava",
  3189: "Sebang",
  3190: "Solite",
  4806: "Sonar",
  4065: "Sonix",
  4807: "Sportrak",
  4808: "V-RICH",
  3191: "Varta",
  4242: "Venom",
  1548: "Vera",
  2423: "Vision",
  3192: "Volcan",
  2424: "Weld Off-Road",
  4809: "WIDEWAY",
  2425: "XD Wheels",
  4276: "YOMAR",
  3530: "Zelda",
  826: "Accelera",
  827: "Achilles",
  828: "Agate",
  932: "Alliance",
  829: "Altenzo",
  1458: "Annaite",
  933: "Apollo",
  830: "Aptany",
  1459: "Ardent",
  831: "Armstrong",
  834: "Atlas",
  835: "Atturo",
  836: "Bearway",
  837: "Bfgoodrich",
  1460: "BKT",
  838: "Blackarrow",
  839: "Blacklion",
  934: "Bridgestone",
  841: "Charmhoo",
  818: "Continental",
  843: "CooperTires",
  1462: "Davanti",
  844: "Deestone",
  1530: "Double Coin",
  1531: "Double Star",
  845: "Dunlop",
  1519: "Duraman",
  846: "Eternity",
  848: "Falken",
  849: "Firestone",
  1518: "Forceum",
  850: "Fortune",
  851: "Frztrac",
  935: "Fulda",
  1512: "Fullrun",
  852: "General Tire",
  853: "GO Pro",
  854: "GoForm",
  855: "Goodride",
  856: "Goodtrip",
  817: "Goodyear",
  857: "Greenmax",
  858: "Greentrac",
  859: "Gripmax",
  860: "Habilead",
  861: "Hankook",
  862: "Headway",
  863: "Hilo",
  864: "Honour",
  1463: "Horizon",
  865: "Ilink",
  866: "Infinity",
  1464: "J Planet",
  867: "Joyroad",
  868: "Kapsen",
  869: "Kenda Tires",
  1520: "King Boss",
  870: "Kumho",
  871: "Landsail",
  872: "Landspider",
  1465: "Lanvigator",
  873: "Lassa",
  874: "Laufenn",
  875: "Leao",
  877: "Long March",
  1507: "Longway",
  1467: "Malone",
  879: "Marshal",
  880: "Massimo",
  881: "Mastercraft",
  882: "Matrax",
  883: "Maxtrek",
  884: "Maxxis",
  1468: "Mayrun",
  885: "Metzeler",
  886: "Michelin",
  887: "Mickey Thompson",
  888: "Miletrip",
  889: "Minnell",
  891: "Montana",
  892: "Nankang",
  893: "Neupar",
  894: "Nexen",
  895: "Nitto",
  897: "Pallyking",
  898: "Pearly",
  899: "Pirelli",
  900: "Prinx",
  902: "Riken",
  903: "Roadcruza",
  904: "Roadking",
  905: "Roadmarch",
  906: "Roadstone",
  907: "Roadx",
  908: "Rotalla",
  1469: "Rydanz",
  909: "Sailwin",
  910: "Seam",
  936: "Shaheen",
  911: "Sportrak",
  912: "Sumitomo",
  913: "Sunny",
  914: "TBB Tires",
  1470: "Teraflex",
  1492: "Tesche",
  915: "Thunderer",
  916: "Toyo",
  917: "Tracmax",
  918: "Trazano",
  937: "Triangle",
  919: "Vitour",
  920: "Vizzoni",
  921: "Vredestein",
  922: "Wanli",
  923: "West Lake",
  924: "Windforce",
  925: "Winrun",
  926: "Yokohama",
  927: "Zeetex",
  928: "Zeta",
  929: "Zetum",
  930: "Zextour",
  931: "Zmax",
  1944: "Amaron",
  1945: "Rhino",
  4184: "Sensus",
  4254: "Prime Way",
  4283: "CST",
};

/**
 * Direct name/alias to logo path map (handles spellings, typos like zeetax -> zeetex, etc.).
 */
export const BRAND_ALIASES: Record<string, string> = {
  "zeetex": "/brands/mgs_brand/z/e/zeetax_1.png",
  "zeetax": "/brands/mgs_brand/z/e/zeetax_1.png",
  "cooper": "/brands/mgs_brand/c/o/coperatie_1.png",
  "coopertires": "/brands/mgs_brand/c/o/coperatie_1.png",
  "hankook": "/brands/mgs_brand/h/a/hankok_1_1.png",
  "hankok": "/brands/mgs_brand/h/a/hankok_1_1.png",
  "yokohama": "/brands/mgs_brand/y/o/yokoma_1.png",
  "yokoma": "/brands/mgs_brand/y/o/yokoma_1.png",
  "bridgestone": "/brands/mgs_brand/b/r/bride_1.png",
  "bride": "/brands/mgs_brand/b/r/bride_1.png",
  "goodyear": "/brands/mgs_brand/g/o/goodyear_1_1_.png",
  "michelin": "/brands/mgs_brand/m/i/michelin_1.png",
  "dunlop": "/brands/mgs_brand/d/u/dunlop_1.png",
  "pirelli": "/brands/mgs_brand/p/i/pirelli_1.png",
  "sailun": "/brands/mgs_brand/s/a/sailun-logo_1.jpg",
  "otani": "/brands/mgs_brand/o/t/otani.jpg",
  "zelda": "/brands/mgs_brand/z/e/zelda.jpg",
  "nexen": "/brands/mgs_brand/n/e/nexen_1_1.png",
  "roadstone": "/brands/mgs_brand/r/o/roadstone_1.png",
  "toyo": "/brands/mgs_brand/t/o/toyo_1.png",
  "falken": "/brands/mgs_brand/f/a/falken_1.png",
  "kumho": "/brands/mgs_brand/k/u/kumho-logo_1.png",
  "continental": "/brands/mgs_brand/c/o/continental.png",
  "accelera": "/brands/mgs_brand/a/c/accelera.png",
  "doublecoin": "/brands/mgs_brand/d/o/double-coin_1.jpg",
  "doublestar": "/brands/mgs_brand/d/o/doublestar-tyres_1.jpg",
  "landspider": "/brands/mgs_brand/l/a/land-spider_1.jpg",
  "laufenn": "/brands/mgs_brand/l/a/laufenn-logo.png",
  "matrax": "/brands/mgs_brand/m/a/matrax-tyres-uae.png",
  "sunny": "/brands/mgs_brand/s/u/sunny_1.jpg",
  "vredestein": "/brands/mgs_brand/v/r/vredestein.jpg",
  "giti": "/brands/mgs_brand/g/i/giti_1.jpg",
  "maxxis": "/brands/mgs_brand/m/a/maxxis.png",
  "bfgoodrich": "/brands/mgs_brand/b/f/bfgoodrich_1.png",
  "landsail": "/brands/mgs_brand/l/a/landsail-logo_1.jpg",
  "arivo": "/brands/mgs_brand/a/r/arivo_1.jpg",
  "roadx": "/brands/mgs_brand/r/o/roadx-logo_1.png",
  "linglong": "/brands/mgs_brand/l/i/linglong_1.jpg",
  "compasal": "/brands/mgs_brand/c/o/compasal_1.jpg",
  "austone": "/brands/mgs_brand/a/u/austone-tires.png",
  "radar": "/brands/mgs_brand/r/a/radar.png",
  "sonix": "/brands/mgs_brand/s/o/sonix_1.jpg",
  "petlas": "/brands/mgs_brand/p/e/petlas_1.jpg",
  "forceum": "/brands/mgs_brand/f/o/forceum_1.jpg",
  "duraman": "/brands/mgs_brand/d/u/duraman-tyres_1.jpg",
  "kingboss": "/brands/mgs_brand/k/i/kingboss.jpg",
  "kustone": "/brands/mgs_brand/k/u/kustone_1.jpg",
  "mileking": "/brands/mgs_brand/m/i/mileking-tyre_1.jpg",
  "rockblade": "/brands/mgs_brand/r/o/rockblade_1.jpg",
  "annaite": "/brands/mgs_brand/a/n/annaite-logo_1.jpg",
  "lanvigator": "/brands/mgs_brand/l/a/lanvigator_1.jpg",
  "royalblack": "/brands/mgs_brand/r/o/royal-black_1__1.png",
  "venom": "/brands/mgs_brand/v/e/venom.png",
  "yomar": "/brands/mgs_brand/y/o/yomar.png",
  "cst": "/brands/mgs_brand/c/s/cst_1_.jpg",
  "imperial": "/brands/mgs_brand/i/m/imperial_1__1.jpg",
  "ceros": "/brands/mgs_brand/c/e/ceros.png",
  "apollo": "/brands/mgs_brand/a/p/apollo-tyres.png",
  "altenzo": "/brands/mgs_brand/a/l/altenzo-logo_1.jpg",
  "amaron": "/brands/mgs_brand/a/m/amaron_logo_0.jpg",
  "armstrong": "/brands/mgs_brand/a/r/armstrong-logo.png",
  "arroyo": "/brands/mgs_brand/a/r/arroyo-logo.png",
  "atlander": "/brands/mgs_brand/a/t/atlander-tyres_1.jpg",
  "atlas": "/brands/mgs_brand/a/t/atlas.jpg",
  "atturo": "/brands/mgs_brand/a/t/atturo.png",
  "bearway": "/brands/mgs_brand/b/e/bearway-logo_1.jpg",
  "blackbear": "/brands/mgs_brand/b/l/blackrhino_1__1_.png",
  "blackrhino": "/brands/mgs_brand/b/l/blackrhino_1__1_.png",
  "bosch": "/brands/mgs_brand/b/o/bosch_1_.png",
  "comforser": "/brands/mgs_brand/c/o/comoro-tyres-dubai_1.jpeg",
  "comoro": "/brands/mgs_brand/c/o/comoro-tyres-dubai_1.jpeg",
  "constancy": "/brands/mgs_brand/c/o/constancy.jpg",
  "crossleader": "/brands/mgs_brand/c/r/crossleader-tyres-shop.png",
  "dagenite": "/brands/mgs_brand/d/a/dagenite_1_.jpg",
  "deestone": "/brands/mgs_brand/d/e/deestone.png",
  "duracell": "/brands/mgs_brand/d/u/duracell_1_.jpg",
  "dynamo": "/brands/mgs_brand/d/u/duraman-tyres_1.jpg",
  "fiamm": "/brands/mgs_brand/f/i/fiamm_1_.jpg",
  "firestone": "/brands/mgs_brand/b/r/bride_1.png",
  "forceland": "/brands/mgs_brand/f/o/forceland_1_.png",
  "fuel": "/brands/mgs_brand/f/u/fuel_1_.png",
  "gepormax": "/brands/mgs_brand/g/e/gepormax.jpg",
  "grandstone": "/brands/mgs_brand/g/r/grandstone_5ca3d3091adf4.jpg",
  "kenda": "/brands/mgs_brand/k/u/kumho-logo_1.png",
  "kapsen": "/brands/mgs_brand/k/a/kapsen-logo.jpg",
  "lassa": "/brands/mgs_brand/l/a/lassalogo.jpg",
  "leao": "/brands/mgs_brand/l/e/leao-logo_1.png",
  "lenso": "/brands/mgs_brand/l/e/lenso-wheels-logo_1_.png",
  "longway": "/brands/mgs_brand/l/o/longway_1.jpg",
  "metzeler": "/brands/mgs_brand/m/e/metzeler-logo_1_.png",
  "mickeythompson": "/brands/mgs_brand/b/f/bfgoodrich_1.png",
  "nankang": "/brands/mgs_brand/n/e/nexen_1_1.png",
  "nitto": "/brands/mgs_brand/t/o/toyo_1.png",
  "prinx": "/brands/mgs_brand/p/r/prinx-tires-logo.jpg",
  "riken": "/brands/mgs_brand/m/i/michelin_1.png",
  "roadcruza": "/brands/mgs_brand/r/o/roadstone_1.png",
  "roadking": "/brands/mgs_brand/r/o/roadking.png",
  "roadmarch": "/brands/mgs_brand/r/o/roadstone_1.png",
  "rotalla": "/brands/mgs_brand/r/o/rotalla-logo.jpg",
  "rotiform": "/brands/mgs_brand/r/o/rotiform_1_.png",
  "sailwin": "/brands/mgs_brand/s/a/sailun-logo_1.jpg",
  "seam": "/brands/mgs_brand/s/e/seam-tyre-logo.png",
  "sensus": "/brands/mgs_brand/s/e/sensus.jpg",
  "solite": "/brands/mgs_brand/s/o/solite_1_.jpg",
  "sportrak": "/brands/mgs_brand/s/u/sunny_1.jpg",
  "sumitomo": "/brands/mgs_brand/d/u/dunlop_1.png",
  "teraflex": "/brands/mgs_brand/t/e/teraflex.jpg",
  "thunderer": "/brands/mgs_brand/t/o/toyo_1.png",
  "tracmax": "/brands/mgs_brand/t/r/tracmax-tyres.jpg",
  "trazano": "/brands/mgs_brand/z/e/zeetax_1.png",
  "triangle": "/brands/mgs_brand/t/o/toyo_1.png",
  "varta": "/brands/mgs_brand/v/a/varta_1_.jpg",
  "vision": "/brands/mgs_brand/v/i/vision_1_.jpg",
  "vitour": "/brands/mgs_brand/v/i/vitour-logo.jpg",
  "volcan": "/brands/mgs_brand/v/o/volcan_1_.png",
  "wanli": "/brands/mgs_brand/w/a/wanli-logo.jpg",
  "windforce": "/brands/mgs_brand/w/i/windforce-logo_1.png",
  "winrun": "/brands/mgs_brand/w/i/winrun.png",
  "zeta": "/brands/mgs_brand/z/e/zeta-logo.jpg",
  "zetum": "/brands/mgs_brand/k/u/kumho-logo_1.png",
  "zextour": "/brands/mgs_brand/z/e/zextour-logo.jpg",
};

export function normaliseBrand(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/**
 * Logo path for an mgs_brand value — accepts either a numeric option id or
 * a brand name, since which one Magento returns varies by store setup.
 */
export function getBrandLogo(brandId?: string | number | null): string | null {
  if (brandId == null || brandId === "") return null;

  const str = String(brandId).trim();
  const asNumber = Number(str);

  // 1. Try numeric ID
  if (Number.isFinite(asNumber) && BRAND_LOGOS[asNumber]) {
    return BRAND_LOGOS[asNumber];
  }

  // 2. Try normalized name / alias
  const norm = normaliseBrand(str);
  if (BRAND_ALIASES[norm]) {
    return BRAND_ALIASES[norm];
  }

  // 3. Fallback: check BRAND_NAMES to find ID
  for (const [id, name] of Object.entries(BRAND_NAMES)) {
    if (normaliseBrand(name) === norm) {
      const logo = BRAND_LOGOS[Number(id)];
      if (logo) return logo;
    }
  }

  return null;
}

/**
 * Returns the brand name for a given mgs_brand ID, or null if not mapped.
 */
export function getBrandName(brandId?: string | number | null): string | null {
  if (brandId == null || brandId === "") return null;
  return BRAND_NAMES[Number(brandId)] ?? null;
}
